name       : milou
version    : 5.23.3
release    : 73
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.3/milou-5.23.3.tar.xz : 0d588be998ff30614b3194169c41aa4cfcb256e511fba3a86309053c57aadb57
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdeclarative-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpackage-devel
    - krunner-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
