name       : milou
version    : 5.23.0
release    : 70
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.0/milou-5.23.0.tar.xz : 115f03b3b9c47206fc09543b7646e93862a6b6bb1c20ff650961f6c16bbe9eb9
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdeclarative-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpackage-devel
    - krunner-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
