name       : milou
version    : 5.12.2
release    : 13
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.2/milou-5.12.2.tar.xz : 88b1ed0e229c243049a5934a42d5cafbdd3f2ca557534b86869a8086c3992cea
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - krunner-devel
    - kservice-devel
    - plasma-framework-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
