name       : milou
version    : 5.17.5
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/milou-5.17.5.tar.xz : b89796e34cc8b6d6d4196169e814249f7b75c1c15763e0b4c1da5c97ccc2c8cf
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kitemmodels-devel
    - krunner-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
