name       : milou
version    : 5.13.4
release    : 21
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.4/milou-5.13.4.tar.xz : 4d7d9f9ac1dacf0c4fbd2e022555fb6e422b1cf29d40d778bca71715d2921c67
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - krunner-devel
    - kservice-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
