name       : milou
version    : 5.12.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.0/milou-5.12.0.tar.xz : 3c95f4e1267e3539be09ee54336097a6ca3fe2af74d0234ea54c930999739bf6
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - krunner-devel
    - kservice-devel
    - plasma-framework-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
