name       : milou
version    : 5.23.5
release    : 75
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/milou-5.23.5.tar.xz : f00540998d172d3c5bbc83ebbfefed676bbd9a9c4a2c733ff9b9d85b18346c15
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdeclarative-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpackage-devel
    - krunner-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
