name       : milou
version    : 5.16.1
release    : 35
source     :
    - https://download.kde.org/stable/plasma/5.16.1/milou-5.16.1.tar.xz : e99556b7253ee3719b980adfe7481c9111741fb79e1b60f7b99679bb2bdbf788
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - krunner-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
